apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}

data:
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.config.mysqlUser | quote }}
