apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}

spec:
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}

  storageClassName: {{ .Values.mysql.storage.storageClass }}

  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
