apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-pv
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.mysql.storage.size }}

  accessModes:
    - {{ .Values.mysql.storage.accessMode }}

  persistentVolumeReclaimPolicy: Retain

  storageClassName: {{ .Values.mysql.storage.storageClass }}

  local:
    path: {{ .Values.mysql.storage.hostPath }}

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.mysql.storage.nodeName }}
