{{- if .Values.networkPolicy.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: wordpress
              app.kubernetes.io/instance: {{ .Release.Name }}

      ports:
        - protocol: TCP
          port: {{ .Values.mysql.service.port }}

{{- end }}
