apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
      protocol: TCP
