apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | quote }}
