apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.wordpress.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}

spec:
  type: {{ .Values.wordpress.service.type }}

  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
      protocol: TCP

      {{- if eq .Values.wordpress.service.type "NodePort" }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
      {{- end }}
