Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # =========================
  # Ubuntu
  # =========================

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.hostname = "wordpress-ubuntu"

    ubuntu.vm.network "private_network",
      ip: "192.168.56.50"

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-ubuntu"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # =========================
  # AlmaLinux 9
  # =========================

  config.vm.define "centos" do |centos|
    centos.vm.box = "almalinux/9"
    centos.vm.hostname = "wordpress-centos"

    centos.vm.network "private_network",
      ip: "192.168.56.60"

    centos.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-centos"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
