# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-server"
      vb.memory = "512"
      vb.cpus = 1
    end
    
    
    server.vm.provision "shell", path: "provision-server.sh"
  end
  
  
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.20"
    
    client.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-client"
      vb.memory = "512"
      vb.cpus = 1
    end
    
    
    client.vm.provision "shell", path: "provision-client.sh"
  end
  
end
